well_map = {
    "A1": {"condition": 'PTX-3 10ng', "replicate": 1, "control_group": False},
    "A10": {"condition": 'COL7A1-R 5ng', "replicate": 4, "control_group": False},
    "A11": {"condition": 'COL7A1-R 5ng', "replicate": 5, "control_group": False},
    "A12": {"condition": 'COL7A1-R 5ng', "replicate": 6, "control_group": False},
    "A2": {"condition": 'PTX-3 10ng', "replicate": 2, "control_group": False},
    "A3": {"condition": 'PTX-3 10ng', "replicate": 3, "control_group": False},
    "A4": {"condition": 'NRP1-R 2000pg', "replicate": 1, "control_group": False},
    "A5": {"condition": 'NRP1-R 2000pg', "replicate": 2, "control_group": False},
    "A6": {"condition": 'NRP1-R 2000pg', "replicate": 3, "control_group": False},
    "A7": {"condition": 'COL7A1-R 5ng', "replicate": 1, "control_group": False},
    "A8": {"condition": 'COL7A1-R 5ng', "replicate": 2, "control_group": False},
    "A9": {"condition": 'COL7A1-R 5ng', "replicate": 3, "control_group": False},
    "B1": {"condition": 'PTX-3 20ng', "replicate": 1, "control_group": False},
    "B10": {"condition": 'COL7A1-R 10ng', "replicate": 4, "control_group": False},
    "B11": {"condition": 'COL7A1-R 10ng', "replicate": 5, "control_group": False},
    "B12": {"condition": 'COL7A1-R 10ng', "replicate": 6, "control_group": False},
    "B2": {"condition": 'PTX-3 20ng', "replicate": 2, "control_group": False},
    "B3": {"condition": 'PTX-3 20ng', "replicate": 3, "control_group": False},
    "B4": {"condition": 'NRP1-R 3000pg', "replicate": 1, "control_group": False},
    "B5": {"condition": 'NRP1-R 3000pg', "replicate": 2, "control_group": False},
    "B6": {"condition": 'NRP1-R 3000pg', "replicate": 3, "control_group": False},
    "B7": {"condition": 'COL7A1-R 10ng', "replicate": 1, "control_group": False},
    "B8": {"condition": 'COL7A1-R 10ng', "replicate": 2, "control_group": False},
    "B9": {"condition": 'COL7A1-R 10ng', "replicate": 3, "control_group": False},
    "C1": {"condition": 'PTX-3 40ng', "replicate": 1, "control_group": False},
    "C10": {"condition": 'COL7A1-R 20ng', "replicate": 4, "control_group": False},
    "C11": {"condition": 'COL7A1-R 20ng', "replicate": 5, "control_group": False},
    "C12": {"condition": 'COL7A1-R 20ng', "replicate": 6, "control_group": False},
    "C2": {"condition": 'PTX-3 40ng', "replicate": 2, "control_group": False},
    "C3": {"condition": 'PTX-3 40ng', "replicate": 3, "control_group": False},
    "C4": {"condition": 'NRP1-R 5000pg', "replicate": 1, "control_group": False},
    "C5": {"condition": 'NRP1-R 5000pg', "replicate": 2, "control_group": False},
    "C6": {"condition": 'NRP1-R 5000pg', "replicate": 3, "control_group": False},
    "C7": {"condition": 'COL7A1-R 20ng', "replicate": 1, "control_group": False},
    "C8": {"condition": 'COL7A1-R 20ng', "replicate": 2, "control_group": False},
    "C9": {"condition": 'COL7A1-R 20ng', "replicate": 3, "control_group": False},
    "D1": {"condition": 'COL7A1-E 3ng', "replicate": 1, "control_group": False},
    "D10": {"condition": 'COL7A1-R 50ng', "replicate": 4, "control_group": False},
    "D11": {"condition": 'COL7A1-R 50ng', "replicate": 5, "control_group": False},
    "D12": {"condition": 'COL7A1-R 50ng', "replicate": 6, "control_group": False},
    "D2": {"condition": 'COL7A1-E 3ng', "replicate": 2, "control_group": False},
    "D3": {"condition": 'COL7A1-E 3ng', "replicate": 3, "control_group": False},
    "D4": {"condition": 'NRP1-E 2000pg', "replicate": 1, "control_group": False},
    "D5": {"condition": 'NRP1-E 2000pg', "replicate": 2, "control_group": False},
    "D6": {"condition": 'NRP1-E 2000pg', "replicate": 3, "control_group": False},
    "D7": {"condition": 'COL7A1-R 50ng', "replicate": 1, "control_group": False},
    "D8": {"condition": 'COL7A1-R 50ng', "replicate": 2, "control_group": False},
    "D9": {"condition": 'COL7A1-R 50ng', "replicate": 3, "control_group": False},
    "E1": {"condition": 'VEGFA-R 555pg', "replicate": 1, "control_group": False},
    "E10": {"condition": None, "replicate": None, "control_group": False},
    "E11": {"condition": None, "replicate": None, "control_group": False},
    "E12": {"condition": None, "replicate": None, "control_group": False},
    "E2": {"condition": 'VEGFA-R 555pg', "replicate": 2, "control_group": False},
    "E3": {"condition": 'VEGFA-R 555pg', "replicate": 3, "control_group": False},
    "E4": {"condition": 'NRP1-E 3000pg', "replicate": 1, "control_group": False},
    "E5": {"condition": 'NRP1-E 3000pg', "replicate": 2, "control_group": False},
    "E6": {"condition": 'NRP1-E 3000pg', "replicate": 3, "control_group": False},
    "E7": {"condition": 'DMEM+SVF', "replicate": 1, "control_group": True},
    "E8": {"condition": 'DMEM vide', "replicate": 1, "control_group": True},
    "E9": {"condition": None, "replicate": None, "control_group": False},
    "F1": {"condition": 'VEGFA-R 1000pg', "replicate": 1, "control_group": False},
    "F10": {"condition": None, "replicate": None, "control_group": False},
    "F11": {"condition": None, "replicate": None, "control_group": False},
    "F12": {"condition": None, "replicate": None, "control_group": False},
    "F2": {"condition": 'VEGFA-R 1000pg', "replicate": 2, "control_group": False},
    "F3": {"condition": 'VEGFA-R 1000pg', "replicate": 3, "control_group": False},
    "F4": {"condition": 'NRP1-E 5000pg', "replicate": 1, "control_group": False},
    "F5": {"condition": 'NRP1-E 5000pg', "replicate": 2, "control_group": False},
    "F6": {"condition": 'NRP1-E 5000pg', "replicate": 3, "control_group": False},
    "F7": {"condition": 'DMEM+SVF', "replicate": 2, "control_group": True},
    "F8": {"condition": 'DMEM vide', "replicate": 2, "control_group": True},
    "F9": {"condition": None, "replicate": None, "control_group": False},
    "G1": {"condition": 'VEGFA-R 4000pg', "replicate": 1, "control_group": False},
    "G10": {"condition": None, "replicate": None, "control_group": False},
    "G11": {"condition": None, "replicate": None, "control_group": False},
    "G12": {"condition": None, "replicate": None, "control_group": False},
    "G2": {"condition": 'VEGFA-R 4000pg', "replicate": 2, "control_group": False},
    "G3": {"condition": 'VEGFA-R 4000pg', "replicate": 3, "control_group": False},
    "G4": {"condition": 'VEGFA-E 555pg', "replicate": 1, "control_group": False},
    "G5": {"condition": 'VEGFA-E 555pg', "replicate": 2, "control_group": False},
    "G6": {"condition": 'VEGFA-E 555pg', "replicate": 3, "control_group": False},
    "G7": {"condition": 'DMEM+SVF', "replicate": 3, "control_group": True},
    "G8": {"condition": 'DMEM vide', "replicate": 3, "control_group": True},
    "G9": {"condition": None, "replicate": None, "control_group": False},
    "H1": {"condition": 'VEGFA-R 8000pg', "replicate": 1, "control_group": False},
    "H10": {"condition": None, "replicate": None, "control_group": False},
    "H11": {"condition": None, "replicate": None, "control_group": False},
    "H12": {"condition": None, "replicate": None, "control_group": False},
    "H2": {"condition": 'VEGFA-R 8000pg', "replicate": 2, "control_group": False},
    "H3": {"condition": 'VEGFA-R 8000pg', "replicate": 3, "control_group": False},
    "H4": {"condition": 'VEGFA-E 750pg', "replicate": 1, "control_group": False},
    "H5": {"condition": 'VEGFA-E 750pg', "replicate": 2, "control_group": False},
    "H6": {"condition": 'VEGFA-E 750pg', "replicate": 3, "control_group": False},
    "H7": {"condition": None, "replicate": None, "control_group": False},
    "H8": {"condition": None, "replicate": None, "control_group": False},
    "H9": {"condition": None, "replicate": None, "control_group": False},
}